#!/bin/bash
# Orbitra HTTPS Configuration Recovery Script
# Restores full Nginx config with HTTPS blocks for domains with SSL

set -e

echo "Orbitra HTTPS Configuration Recovery"
echo "====================================="

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run this script as root (use sudo)"
  exit 1
fi

# Check if orbitra directory exists
if [ ! -d "/var/www/orbitra" ]; then
    echo "ERROR: /var/www/orbitra not found"
    exit 1
fi

# Check if database exists
if [ ! -f "/var/www/orbitra/orbitra_db.sqlite" ]; then
    echo "ERROR: Database not found"
    exit 1
fi

echo "Checking for SSL certificates..."

# Find all domains with SSL certificates
SSL_DOMAINS=()
for cert_dir in /etc/letsencrypt/live/*/; do
    if [ -d "$cert_dir" ]; then
        domain=$(basename "$cert_dir")
        if [ "$domain" != "README" ] && [ -f "$cert_dir/fullchain.pem" ]; then
            SSL_DOMAINS+=("$domain")
        fi
    fi
done

if [ ${#SSL_DOMAINS[@]} -eq 0 ]; then
    echo "No SSL certificates found. Only HTTP config will be generated."
    HAS_SSL=false
else
    echo "Found SSL certificates for domains:"
    for domain in "${SSL_DOMAINS[@]}"; do
        echo "  - $domain"
    done
    HAS_SSL=true
fi

# Get PHP version
PHP_V=$(php -v | head -n 1 | cut -d " " -f 2 | cut -f1-2 -d".")
PHP_FPM_SOCK="/var/run/php/php${PHP_V}-fpm.sock"

# Get all domains from database (fallback)
ALL_DOMAINS=$(sqlite3 /var/www/orbitra/orbitra_db.sqlite "SELECT name FROM domains WHERE name IS NOT NULL AND name != '' ORDER BY name" 2>/dev/null || echo "")

echo "Generating Nginx configuration..."

# Generate config file
CONFIG_FILE="/etc/nginx/sites-available/orbitra"

# Write HTTP server block
{
    echo "# Auto-generated by Orbitra - DO NOT EDIT MANUALLY"
    echo ""
    echo "server {"
    echo "    listen 80 default_server;"
    echo "    server_name _;"

    # Add domains from database
    if [ -n "$ALL_DOMAINS" ]; then
        echo "$ALL_DOMAINS" | while read -r domain; do
            if [ -n "$domain" ]; then
                echo "    server_name _ $domain;"
            fi
        done
    fi

    echo "    root /var/www/orbitra;"
    echo "    index index.php admin.php index.html;"
    echo ""
    echo "    # Access to React/Vite static files"
    echo "    location /frontend/dist/ {"
    echo "        alias /var/www/orbitra/frontend/dist/;"
    echo "        try_files \$uri \$uri/ /frontend/dist/index.html;"
    echo "    }"
    echo ""
    echo "    # Router handling (API and clicks)"
    echo "    location / {"
    echo "        try_files \$uri \$uri/ /index.php?\$query_string;"
    echo "    }"
    echo ""
    echo "    # Allow large file uploads for Geo DB"
    echo "    client_max_body_size 256m;"
    echo ""
    echo "    # PHP processing"
    echo "    location ~ \.php$ {"
    echo "        include snippets/fastcgi-php.conf;"
    echo "        fastcgi_pass unix:$PHP_FPM_SOCK;"
    echo "        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;"
    echo "        include fastcgi_params;"
    echo "    }"
    echo ""
    echo "    # Deny access to SQLite DB and configurations"
    echo "    location ~ \.sqlite$ {"
    echo "        deny all;"
    echo "    }"
    echo "    location ~ /\. {"
    echo "        deny all;"
    echo "    }"
    echo "}"
} > "$CONFIG_FILE"

# Append HTTPS server blocks for domains with SSL
if [ "$HAS_SSL" = true ]; then
    for domain in "${SSL_DOMAINS[@]}"; do
        {
            echo ""
            echo "server {"
            echo "    listen 443 ssl;"
            echo "    server_name $domain;"
            echo ""
            echo "    # SSL certificates"
            echo "    ssl_certificate /etc/letsencrypt/live/$domain/fullchain.pem;"
            echo "    ssl_certificate_key /etc/letsencrypt/live/$domain/privkey.pem;"
            echo "    include /etc/letsencrypt/options-ssl-nginx.conf;"
            echo "    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;"
            echo ""
            echo "    root /var/www/orbitra;"
            echo "    index index.php admin.php index.html;"
            echo ""
            echo "    # Access to React/Vite static files"
            echo "    location /frontend/dist/ {"
            echo "        alias /var/www/orbitra/frontend/dist/;"
            echo "        try_files \$uri \$uri/ /frontend/dist/index.html;"
            echo "    }"
            echo ""
            echo "    # Router handling (API and clicks)"
            echo "    location / {"
            echo "        try_files \$uri \$uri/ /index.php?\$query_string;"
            echo "    }"
            echo ""
            echo "    # Allow large file uploads for Geo DB"
            echo "    client_max_body_size 256m;"
            echo ""
            echo "    # PHP processing"
            echo "    location ~ \.php$ {"
            echo "        include snippets/fastcgi-php.conf;"
            echo "        fastcgi_pass unix:$PHP_FPM_SOCK;"
            echo "        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;"
            echo "        include fastcgi_params;"
            echo "    }"
            echo ""
            echo "    # Deny access to SQLite DB and configurations"
            echo "    location ~ \.sqlite$ {"
            echo "        deny all;"
            echo "    }"
            echo "    location ~ /\. {"
            echo "        deny all;"
            echo "    }"
            echo "}"
        } >> "$CONFIG_FILE"
    done
fi

# Test and reload Nginx
echo "Testing Nginx configuration..."
nginx -t

echo "Reloading Nginx..."
systemctl reload nginx

echo ""
echo "✅ HTTPS configuration restored successfully!"
echo ""
if [ "$HAS_SSL" = true ]; then
    echo "HTTPS enabled for domains:"
    for domain in "${SSL_DOMAINS[@]}"; do
        echo "  https://$domain"
    done
fi
echo ""
echo "Test your campaign:"
echo "  curl -I https://orbitra.net.ru/t6wa4f"
echo ""
