#!/bin/bash
# Orbitra HTTPS Configuration Recovery Script
# Restores full Nginx config with HTTPS blocks for domains with SSL

set -e

echo "Orbitra HTTPS Configuration Recovery"
echo "====================================="

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo "Please run this script as root (use sudo)"
  exit 1
fi

# Check if orbitra directory exists
if [ ! -d "/var/www/orbitra" ]; then
    echo "ERROR: /var/www/orbitra not found"
    exit 1
fi

# Check if database exists
if [ ! -f "/var/www/orbitra/orbitra_db.sqlite" ]; then
    echo "ERROR: Database not found"
    exit 1
fi

echo "Checking for SSL certificates..."

# Find all domains with SSL certificates
SSL_DOMAINS=()
for cert_dir in /etc/letsencrypt/live/*/; do
    if [ -d "$cert_dir" ]; then
        domain=$(basename "$cert_dir")
        if [ "$domain" != "README" ] && [ -f "$cert_dir/fullchain.pem" ]; then
            SSL_DOMAINS+=("$domain")
        fi
    fi
done

if [ ${#SSL_DOMAINS[@]} -eq 0 ]; then
    echo "No SSL certificates found. Only HTTP config will be generated."
    HAS_SSL=false
else
    echo "Found SSL certificates for domains:"
    for domain in "${SSL_DOMAINS[@]}"; do
        echo "  - $domain"
    done
    HAS_SSL=true
fi

# Get PHP version
PHP_V=$(php -v | head -n 1 | cut -d " " -f 2 | cut -f1-2 -d".")
PHP_FPM_SOCK="/var/run/php/php${PHP_V}-fpm.sock"

# Get all domains from database (fallback)
ALL_DOMAINS=$(sqlite3 /var/www/orbitra/orbitra_db.sqlite "SELECT name FROM domains WHERE name IS NOT NULL AND name != '' ORDER BY name" 2>/dev/null || echo "")

echo "Generating Nginx configuration..."

# Generate HTTP server block (all domains)
CONFIG="# Auto-generated by Orbitra - DO NOT EDIT MANUALLY\n\n"

# HTTP server block
CONFIG+="server {\n"
CONFIG+="    listen 80 default_server;\n"
CONFIG+="    server_name _;\n"
if [ -n "$ALL_DOMAINS" ]; then
    # Convert to space-separated list
    DOMAIN_LIST=$(echo "$ALL_DOMAINS" | tr '\n' ' ')
    CONFIG+="    server_name _ $DOMAIN_LIST;\n"
fi
CONFIG+="    root /var/www/orbitra;\n"
CONFIG+="    index index.php admin.php index.html;\n\n"

CONFIG+="    # Access to React/Vite static files\n"
CONFIG+="    location /frontend/dist/ {\n"
CONFIG+="        alias /var/www/orbitra/frontend/dist/;\n"
CONFIG+="        try_files \\\$uri \\\$uri/ /frontend/dist/index.html;\n"
CONFIG+="    }\n\n"

CONFIG+="    # Router handling (API and clicks)\n"
CONFIG+="    location / {\n"
CONFIG+="        try_files \\\$uri \\\$uri/ /index.php?\\\$query_string;\n"
CONFIG+="    }\n\n"

CONFIG+="    # Allow large file uploads for Geo DB\n"
CONFIG+="    client_max_body_size 256m;\n\n"

CONFIG+="    # PHP processing\n"
CONFIG+="    location ~ \.php$ {\n"
CONFIG+="        include snippets/fastcgi-php.conf;\n"
CONFIG+="        fastcgi_pass unix:$PHP_FPM_SOCK;\n"
CONFIG+="        fastcgi_param SCRIPT_FILENAME \\\$document_root\\\$fastcgi_script_name;\n"
CONFIG+="        include fastcgi_params;\n"
CONFIG+="    }\n\n"

CONFIG+="    # Deny access to SQLite DB and configurations\n"
CONFIG+="    location ~ \.sqlite$ {\n"
CONFIG+="        deny all;\n"
CONFIG+="    }\n"
CONFIG+="    location ~ /\. {\n"
CONFIG+="        deny all;\n"
CONFIG+="    }\n"
CONFIG+="}\n\n"

# HTTPS server blocks for domains with SSL
if [ "$HAS_SSL" = true ]; then
    for domain in "${SSL_DOMAINS[@]}"; do
        CONFIG+="server {\n"
        CONFIG+="    listen 443 ssl;\n"
        CONFIG+="    server_name $domain;\n\n"

        # SSL certificates
        CONFIG+="    ssl_certificate /etc/letsencrypt/live/$domain/fullchain.pem;\n"
        CONFIG+="    ssl_certificate_key /etc/letsencrypt/live/$domain/privkey.pem;\n"
        CONFIG+="    include /etc/letsencrypt/options-ssl-nginx.conf;\n"
        CONFIG+="    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;\n\n"

        CONFIG+="    root /var/www/orbitra;\n"
        CONFIG+="    index index.php admin.php index.html;\n\n"

        CONFIG+="    # Access to React/Vite static files\n"
        CONFIG+="    location /frontend/dist/ {\n"
        CONFIG+="        alias /var/www/orbitra/frontend/dist/;\n"
        CONFIG+="        try_files \\\$uri \\\$uri/ /frontend/dist/index.html;\n"
        CONFIG+="    }\n\n"

        CONFIG+="    # Router handling (API and clicks)\n"
        CONFIG+="    location / {\n"
        CONFIG+="        try_files \\\$uri \\\$uri/ /index.php?\\\$query_string;\n"
        CONFIG+="    }\n\n"

        CONFIG+="    # Allow large file uploads for Geo DB\n"
        CONFIG+="    client_max_body_size 256m;\n\n"

        CONFIG+="    # PHP processing\n"
        CONFIG+="    location ~ \.php$ {\n"
        CONFIG+="        include snippets/fastcgi-php.conf;\n"
        CONFIG+="        fastcgi_pass unix:$PHP_FPM_SOCK;\n"
        CONFIG+="        fastcgi_param SCRIPT_FILENAME \\\$document_root\\\$fastcgi_script_name;\n"
        CONFIG+="        include fastcgi_params;\n"
        CONFIG+="    }\n\n"

        CONFIG+="    # Deny access to SQLite DB and configurations\n"
        CONFIG+="    location ~ \.sqlite$ {\n"
        CONFIG+="        deny all;\n"
        CONFIG+="    }\n"
        CONFIG+="    location ~ /\. {\n"
        CONFIG+="        deny all;\n"
        CONFIG+="    }\n"
        CONFIG+="}\n\n"
    done
fi

# Write config
echo "$CONFIG" > /etc/nginx/sites-available/orbitra

# Test and reload Nginx
echo "Testing Nginx configuration..."
nginx -t

echo "Reloading Nginx..."
systemctl reload nginx

echo ""
echo "✅ HTTPS configuration restored successfully!"
echo ""
if [ "$HAS_SSL" = true ]; then
    echo "HTTPS enabled for domains:"
    for domain in "${SSL_DOMAINS[@]}"; do
        echo "  https://$domain"
    done
fi
echo ""
echo "Test your campaign:"
echo "  curl -I https://orbitra.net.ru/t6wa4f"
echo ""
