// Generates mcp/tools.json — the tool manifest consumed by the tracker's own
// HTTP MCP endpoint (mcp.php).
//
// Why generate instead of hand-writing: index.js stays the single source of truth
// for what the tools are. Descriptions and JSON Schemas are read straight off the
// running server (the same payload a client sees in tools/list), and the api.php
// route each tool maps to is extracted from this file's source. Anything that
// cannot be resolved automatically is listed in ROUTE_OVERRIDES below and must be
// implemented by hand on the PHP side too.
//
//   node src/manifest.js          write mcp/tools.json
//   node src/manifest.js --check   fail if the committed file is out of date
//
// Run --check after touching the tool list; a stale manifest means the HTTP
// endpoint and the local server disagree about what Orbitra can do.

import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { readFileSync, writeFileSync } from 'node:fs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = join(__dirname, '..', 'tools.json');

// Tools whose handler does more than forward one call. Each needs a matching
// implementation in mcp.php; "steps" documents what that implementation must do
// so the two cannot silently diverge in behaviour.
const ROUTE_OVERRIDES = {
  orbitra_update_campaign: {
    handler: 'update_campaign',
    steps: ['GET get_campaign', 'merge fields + normalise streams', 'POST save_campaign'],
  },
  orbitra_update_offer: {
    handler: 'update_offer',
    steps: ['GET get_offer', 'merge passed fields over current', 'POST save_offer'],
  },
  orbitra_bulk_create_campaigns: {
    handler: 'bulk_create_campaigns',
    steps: ['POST save_campaign once per item', 'collect per-item ok/error'],
  },
  orbitra_api_request: {
    handler: 'api_request',
    steps: ['forward an arbitrary action chosen by the caller'],
  },
};

// Pull "apiGet('x'" / "apiPost('x'" out of each tool block in index.js.
function extractRoutes() {
  const src = readFileSync(join(__dirname, 'index.js'), 'utf8');
  const blocks = src.split(/\ntool\(\n/).slice(1);
  const routes = {};
  for (const block of blocks) {
    const body = block.split('\n);')[0];
    const name = body.match(/'([a-z0-9_]+)'/)?.[1];
    if (!name) continue;
    const calls = [...body.matchAll(/api(Get|Post)\(\s*'([a-z0-9_]+)'/g)]
      .map((m) => ({ method: m[1] === 'Get' ? 'GET' : 'POST', action: m[2] }));
    routes[name] = calls;
  }
  return routes;
}

async function main() {
  const transport = new StdioClientTransport({
    command: process.execPath,
    args: [join(__dirname, 'index.js')],
    env: { ...process.env },
  });
  const client = new Client({ name: 'orbitra-manifest', version: '1.0.0' });
  await client.connect(transport);
  const { tools } = await client.listTools();
  await client.close();

  const routes = extractRoutes();
  const unresolved = [];

  const entries = tools
    .slice()
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((t) => {
      const entry = {
        name: t.name,
        description: t.description,
        inputSchema: t.inputSchema,
      };
      if (ROUTE_OVERRIDES[t.name]) {
        Object.assign(entry, ROUTE_OVERRIDES[t.name]);
      } else {
        const calls = routes[t.name] || [];
        if (calls.length !== 1) {
          unresolved.push(`${t.name} (${calls.length} api calls found, expected exactly 1)`);
          return entry;
        }
        entry.method = calls[0].method;
        entry.action = calls[0].action;
      }
      return entry;
    });

  if (unresolved.length) {
    console.error(
      '✗ Could not derive a route for:\n  ' + unresolved.join('\n  ') +
      '\n\nAdd them to ROUTE_OVERRIDES in src/manifest.js and implement them in mcp.php.'
    );
    process.exit(1);
  }

  const manifest = {
    _comment: 'GENERATED by mcp/src/manifest.js from mcp/src/index.js. Do not edit by hand — run: node src/manifest.js',
    generatedFrom: 'mcp/src/index.js',
    toolCount: entries.length,
    tools: entries,
  };
  const json = JSON.stringify(manifest, null, 2) + '\n';

  if (process.argv.includes('--check')) {
    let current = '';
    try {
      current = readFileSync(OUT, 'utf8');
    } catch {
      /* missing counts as out of date */
    }
    if (current !== json) {
      console.error('✗ tools.json is out of date. Run: node src/manifest.js');
      process.exit(1);
    }
    console.log(`✔ tools.json is current (${entries.length} tools).`);
    process.exit(0);
  }

  writeFileSync(OUT, json);
  console.log(`✔ Wrote ${OUT} (${entries.length} tools, ${Object.keys(ROUTE_OVERRIDES).length} hand-written).`);
  process.exit(0);
}

main().catch((err) => {
  console.error('✗ manifest generation failed:', err);
  process.exit(1);
});
